import type { Metadata, NextPage } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import Header from "@/components/header/header"
import { type PropsWithChildren } from "react"
import { readCurrency } from "@/entities/currency/server-actions"
import CurrencyProvider from "@/entities/currency/currency-provider"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout: NextPage<PropsWithChildren> = async ({ children }) => {
  const currency = await readCurrency()

  return (
    <html
      lang="ru"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <CurrencyProvider initialValue={currency}>
        <body className="min-h-full flex flex-col">
          <Header />
          {children}
        </body>
      </CurrencyProvider>
    </html>
  )
}

export default RootLayout
